[package]
name = "cargo-clippy"
version = "0.1.0"
authors = ["Ray Solomon <raybsolomon@gmail.com>"]
license = "MIT"
readme = "README.md"

[dependencies]
clippy = { git = "https://github.com/Manishearth/rust-clippy" }
glob = "0.2"
